			--BaiTap1--
		--QuanLyBanHang--
	CREATE DATABASE QLBH

	CREATE TABLE KHACHHANG
	(
		MAKH	char(4),
		HOTEN	varchar(40),
		DCHI	varchar(50),
		SODT	varchar(20),
		NGSINH	smalldatetime,
		NGDK	smalldatetime,
		DOANHSO	money,
		PRIMARY KEY (MAKH),
	)

	CREATE TABLE NHANVIEN
	(
		MANV	char(4),
		HOTEN	varchar(40),
		SODT	varchar(20),
		NGVL	smalldatetime,
		PRIMARY KEY (MANV),
	)

	CREATE TABLE SANPHAM
	(
		MASP	char(4),
		TENSP	varchar(40),
		DVT		varchar(20),
		NUOCSX	varchar(40),
		GIA		money,
		PRIMARY KEY (MASP),
	)


	CREATE TABLE HOADON
	(
		SOHD	int,
		NGHD	smalldatetime,
		MAKH	char(4),
		MANV	char(4),
		TRIGIA	money,
		PRIMARY KEY (SOHD),
	)

	CREATE TABLE CTHD
	(
		SOHD	int,
		MASP	char(4),
		SL		int,
		PRIMARY KEY (SOHD, MASP)
	)



	--QUANLYGIAOVU--
	CREATE DATABASE QLGV


	CREATE TABLE KHOA 
	(
		MAKHOA	varchar(4),
		TENKHOA	varchar(40),
		NGTLAP	smalldatetime,
		TRGKHOA	char(4),
	)


	CREATE TABLE MONHOC
	(
		MAMH	char(4),
		TENMH	varchar(40),
		TCLT	tinyint,
		TCTH	tinyint,
		MAKHOA varchar(4),

	)

	CREATE TABLE DIEUKIEN
	(
		MAMH			varchar(10),
		MAMH_TRUOC		varchar (10),
	)


	CREATE TABLE GIAOVIEN
	(
		MAGV		char(4),
		HOTEN		varchar(40),
		HOCVI		varchar(10),
		HOCHAM		varchar(10),
		GIOITINH	varchar(3),
		NGSINH		smalldatetime,
		NGVL		smalldatetime,
		HESO		numeric(4,2),
		MUCLUONG	money,
		MAKHOA		varchar(4),
	)


	CREATE TABLE LOP
	(
		MALOP	char(3),
		TENLOP	varchar(40),
		TRGLOP	char(5),
		SISO	tinyint,
		MAGVCN	char(4),
	)

	CREATE TABLE HOCVIEN
	(
		MAHV		char(5),
		HO			varchar(40),
		TEN			varchar(10),
		NGSINH		smalldatetime,
		GIOITINH	varchar(3),
		NOISINH		varchar(40),
		MALOP		char (3),
	)

	CREATE TABLE GIANGDAY
	(
		MALOP	char(3),
		MAMH	varchar(10),
		MAGV	char(4),
		HOCKY	tinyint,
		NAM		smallint,
		TUNGAY	smalldatetime,
		DENNGAY	smalldatetime,
	)


	CREATE TABLE KETQUATHI
	(
		MAHV	char(5),
		MAMH	varchar(10),
		LANTHI	tinyint,
		NGTHI	smalldatetime,
		DIEM	numeric(4,2),
		KQUA	varchar(10),
	)


	ALTER TABLE HOCVIEN
	ALTER COLUMN MAHV char(5) NOT NULL;
	ALTER TABLE HOCVIEN ADD
	CONSTRAINT PK_HV PRIMARY KEY (MAHV);

	ALTER TABLE LOP
	ALTER COLUMN MALOP char(3) NOT NULL;
	ALTER TABLE LOP ADD
	CONSTRAINT PK_LOP PRIMARY KEY (MALOP);

	ALTER TABLE KHOA
	ALTER COLUMN MAKHOA varchar(4) NOT NULL;
	ALTER TABLE KHOA ADD
	CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA);
	

	ALTER TABLE MONHOC
	ALTER COLUMN MAMH varchar(10) NOT NULL;
	ALTER TABLE MONHOC ADD
	CONSTRAINT PK_MH PRIMARY KEY (MAMH);
	

	ALTER TABLE DIEUKIEN
	ALTER COLUMN MAMH varchar(10) NOT NULL;
	ALTER TABLE DIEUKIEN
	ALTER COLUMN MAMH_TRUOC varchar(10) NOT NULL;
	ALTER TABLE DIEUKIEN ADD
	CONSTRAINT PK_DK PRIMARY KEY (MAMH, MAMH_TRUOC);
	
	
	
	ALTER TABLE DIEUKIEN
	DROP COLUMN MAHDO_TRUOC

	ALTER TABLE GIAOVIEN
	ALTER COLUMN MAGV char(4) NOT NULL;
	ALTER TABLE GIAOVIEN ADD
	CONSTRAINT PK_GV PRIMARY KEY (MAGV);

	ALTER TABLE GIANGDAY
	ALTER COLUMN MALOP char(3) NOT NULL;
	ALTER TABLE GIANGDAY
	ALTER COLUMN MAMH varchar(10) NOT NULL;
	ALTER TABLE GIANGDAY ADD
	CONSTRAINT PK_GD PRIMARY KEY (MALOP, MAMH);

	ALTER TABLE KETQUATHI
	ALTER COLUMN MAHV char(5) NOT NULL;
	ALTER TABLE KETQUATHI
	ALTER COLUMN MAMH varchar(10) NOT NULL;
	ALTER TABLE KETQUATHI
	ALTER COLUMN LANTHI tinyint NOT NULL;
	ALTER TABLE KETQUATHI ADD
	CONSTRAINT PK_KQ PRIMARY KEY (MAHV, MAMH, LANTHI);

	ALTER TABLE HOCVIEN
	ADD GHICHU varchar(50);
	ALTER TABLE HOCVIEN
	ADD DIEMTB real;
	ALTER TABLE HOCVIEN
	ADD XEPLOAI char(5);

	--Cau 1 QULBH--
	ALTER TABLE HOADON ADD
	CONSTRAINT FK_HD_KH FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH);
	ALTER TABLE HOADON ADD
	CONSTRAINT FK_HD_NV FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV);
	ALTER TABLE CTHD ADD
	CONSTRAINT FK_CTHD_SP FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP);
	ALTER TABLE CTHD ADD
	CONSTRAINT FK_CTHD_HD FOREIGN KEY(SOHD) REFERENCES HOADON(SOHD);

				--Bai 2--
			--QuanLyBanHang--
	--CAU 2--
	ALTER TABLE SANPHAM 
	ADD GHICHU varchar(20);
	--Cau 3--
	ALTER TABLE KHACHHANG 
	ADD LOAIKH tinyint;
	--Cau 4--
	ALTER TABLE SANPHAM
	ALTER COLUMN GHICHU varchar(100);
	--Cau 5--
	ALTER TABLE SANPHAM
	DROP COLUMN GHICHU;
	--Cau 6--
	ALTER TABLE KHACHHANG
	ADD CONSTRAINT CHECK_LOAIKH CHECK (LOAIKH='Vang lai' OR LOAIKH='Thuong xuyen' OR LOAIKH='Vip');
	--Cau 7--
	ALTER TABLE SANPHAM
	ADD CONSTRAINT CHECK_DVT CHECK(DVT='CAY'OR DVT='CAI'OR DVT='HOP'OR DVT='QUYEN'OR DVT='CHUC');
	--Cau 8--
	ALTER TABLE SANPHAM 
	ADD CONSTRAINT CHECK_GIA CHECK(GIA>=500);
	--Cau 9--
	ALTER TABLE HOADON
	ADD CONSTRAINT CHK_MUAHANG CHECK (TRIGIA > 0);
	--Cau 10--
	ALTER TABLE KHACHHANG
	ADD CONSTRAINT CHECK_NGDK CHECK(NGDK>NGSINH);

			--QuanLyGiaoVu--

	--Cau 1--
	ALTER TABLE HOCVIEN ADD
	CONSTRAINT FK_HV_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);
	ALTER TABLE LOP ADD
	CONSTRAINT FK_LOP_GV FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV);
	ALTER TABLE LOP ADD
	CONSTRAINT FK_TRGLOP FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN(MAHV);
	ALTER TABLE GIAOVIEN ADD 
	CONSTRAINT FK_MAKHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);
	ALTER TABLE GIANGDAY ADD 
	CONSTRAINT FK_MAMH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH);
	ALTER TABLE KHOA ADD 
	CONSTRAINT FK_MAGV FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV);
	ALTER TABLE MONHOC ADD
	CONSTRAINT FK_MAKHOA_2 FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);
	ALTER TABLE DIEUKIEN ADD 
	CONSTRAINT FK_MAMH_TRUOC FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH);
	ALTER TABLE DIEUKIEN ADD
	CONSTRAINT FK_DK_MAMH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH);
	ALTER TABLE KETQUATHI ADD
	CONSTRAINT FK_MAHV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV);

	--Cau 3--
	ALTER TABLE HOCVIEN ADD
	CONSTRAINT CHECK_GT CHECK(GIOITINH IN ('Nam', 'Nu'));
	ALTER TABLE GIAOVIEN ADD
	CONSTRAINT CHECK_GTGV CHECK(GIOITINH IN('Nam', 'Nu'));
	--Cau 4--
	ALTER TABLE KETQUATHI ADD
	CONSTRAINT CHECK_DIEM CHECK 
	(
		DIEM BETWEEN 0 AND 10
		AND RIGHT(CAST(DIEM AS VARCHAR), 3) LIKE '.__'
	)
	--Cau 5--
	ALTER TABLE KETQUATHI ADD 
	CONSTRAINT CHECK_KETQUA CHECK
	(	
		(KQUA = 'Dat' AND DIEM BETWEEN 5 AND 10)
		OR (KQUA = 'Khong dat' AND DIEM < 5)
	)
	--Cau 6--
	ALTER TABLE KETQUATHI ADD
	CONSTRAINT CHECK_LANTHI CHECK (LANTHI <=3);
	--Cau 7--
	ALTER TABLE GIANGDAY ADD
	CONSTRAINT CHECK_HK CHECK (HOCKY BETWEEN 1 AND 3);
	--Cau 8--
	ALTER TABLE GIAOVIEN ADD
	CONSTRAINT CHECK_HOCVi CHECK (HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS'));