			--BaiTap1--
		--QuanLyBanHang--
	CREATE DATABASE QLBH

	CREATE TABLE KHACHHANG
	(
		MAKH	char(4),
		HOTEN	varchar(40),
		DCHI	varchar(50),
		SODT	varchar(20),
		NGSINH	smalldatetime,
		NGDK	smalldatetime,
		DOANHSO	money,
		PRIMARY KEY (MAKH),
	)

	CREATE TABLE NHANVIEN
	(
		MANV	char(4),
		HOTEN	varchar(40),
		SODT	varchar(20),
		NGVL	smalldatetime,
		PRIMARY KEY (MANV),
	)

	CREATE TABLE SANPHAM
	(
		MASP	char(4),
		TENSP	varchar(40),
		DVT		varchar(20),
		NUOCSX	varchar(40),
		GIA		money,
		PRIMARY KEY (MASP),
	)


	CREATE TABLE HOADON
	(
		SOHD	int,
		NGHD	smalldatetime,
		MAKH	char(4),
		MANV	char(4),
		TRIGIA	money,
		PRIMARY KEY (SOHD),
	)

	CREATE TABLE CTHD
	(
		SOHD	int,
		MASP	char(4),
		SL		int,
		PRIMARY KEY (SOHD, MASP)
	)



	--QUANLYGIAOVU--
	CREATE DATABASE QLGV


		-- Tạo bảng KHOA
	CREATE TABLE KHOA 
	(
		MAKHOA VARCHAR(4),
		TENKHOA VARCHAR(40),
		NGTLAP SMALLDATETIME,
		TRGKHOA CHAR(4)
		CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA)
	)
	GO

	-- Tạo bảng MONHOC
	CREATE TABLE MONHOC
	(
		MAMH VARCHAR(10),
		TENMH VARCHAR(40),
		TCLT TINYINT,
		TCTH TINYINT,
		MAKHOA VARCHAR(4),
		CONSTRAINT PK_MONHOC PRIMARY KEY (MAMH),
	)
	GO

	-- Tạo bảng DIEUKIEN
	CREATE TABLE DIEUKIEN
	(
		MAMH VARCHAR(10),
		MAMH_TRUOC VARCHAR(10),
		CONSTRAINT PK_DIEUKIEN PRIMARY KEY (MAMH, MAMH_TRUOC)
	)
	GO

	-- Tạo bảng GIAOVIEN
	CREATE TABLE GIAOVIEN
	(
		MAGV CHAR(4),
		HOTEN VARCHAR(40),
		HOCVI VARCHAR(10),
		HOCHAM VARCHAR(10),
		GIOITINH VARCHAR(3),
		NGSINH SMALLDATETIME,
		NGVL SMALLDATETIME,
		HESO NUMERIC(4,2),
		MUCLUONG MONEY,
		MAKHOA VARCHAR(4)
		CONSTRAINT PK_GIAOVIEN PRIMARY KEY (MAGV)
	)
	GO

	-- Tạo bảng HOCVIEN
	CREATE TABLE HOCVIEN
	(
		MAHV CHAR(5),
		HO VARCHAR(40),
		TEN VARCHAR(10),
		NGSINH SMALLDATETIME,
		GIOITINH VARCHAR(3),
		NOISINH VARCHAR(40),
		MALOP CHAR(3),
		CONSTRAINT PK_HOCVIEN PRIMARY KEY (MAHV)
	)
	GO

	-- Tạo bảng LOP
	CREATE TABLE LOP
	(
		MALOP CHAR(3),
		TENLOP VARCHAR(40),
		TRGLOP CHAR(5),
		SISO TINYINT,
		MAGVCN CHAR(4)
		CONSTRAINT PK_LOP PRIMARY KEY (MALOP)
	)
	GO

	-- Tạo bảng GIANGDAY
	CREATE TABLE GIANGDAY
	(
		MALOP CHAR(3),
		MAMH VARCHAR(10),
		MAGV CHAR(4),
		HOCKY TINYINT,
		NAM SMALLINT,
		TUNGAY SMALLDATETIME,
		DENNGAY SMALLDATETIME
		CONSTRAINT PK_GIANGDAY PRIMARY KEY (MALOP, MAMH),
	)
	GO

	-- Tạo bảng KETQUATHI
	CREATE TABLE KETQUATHI
	(
		MAHV CHAR(5),
		MAMH VARCHAR(10),
		LANTHI TINYINT,
		NGTHI SMALLDATETIME,
		DIEM NUMERIC(4,2),
		KQUA VARCHAR(10)
		CONSTRAINT PK_KETQUATHI PRIMARY KEY (MAHV, MAMH, LANTHI)
	)
	GO


	ALTER TABLE HOCVIEN
	ADD GHICHU varchar(50);
	ALTER TABLE HOCVIEN
	ADD DIEMTB real;
	ALTER TABLE HOCVIEN
	ADD XEPLOAI char(5);

	--Cau 1 QULBH--
	ALTER TABLE HOADON ADD
	CONSTRAINT FK_HD_KH FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH);
	ALTER TABLE HOADON ADD
	CONSTRAINT FK_HD_NV FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV);
	ALTER TABLE CTHD ADD
	CONSTRAINT FK_CTHD_SP FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP);
	ALTER TABLE CTHD ADD
	CONSTRAINT FK_CTHD_HD FOREIGN KEY(SOHD) REFERENCES HOADON(SOHD);

				--Bai 2--
			--QuanLyBanHang--
	--CAU 2--
	ALTER TABLE SANPHAM 
	ADD GHICHU varchar(20);
	--Cau 3--
	ALTER TABLE KHACHHANG 
	ADD LOAIKH tinyint;
	--Cau 4--
	ALTER TABLE SANPHAM
	ALTER COLUMN GHICHU varchar(100);
	--Cau 5--
	ALTER TABLE SANPHAM
	DROP COLUMN GHICHU;
	--Cau 6--
	ALTER TABLE KHACHHANG
	ADD CONSTRAINT CHECK_LOAIKH CHECK (LOAIKH='Vang lai' OR LOAIKH='Thuong xuyen' OR LOAIKH='Vip');
	--Cau 7--
	ALTER TABLE SANPHAM
	ADD CONSTRAINT CHECK_DVT CHECK(DVT='CAY'OR DVT='CAI'OR DVT='HOP'OR DVT='QUYEN'OR DVT='CHUC');
	--Cau 8--
	ALTER TABLE SANPHAM 
	ADD CONSTRAINT CHECK_GIA CHECK(GIA>=500);
	--Cau 9--
	ALTER TABLE HOADON
	ADD CONSTRAINT CHK_MUAHANG CHECK (TRIGIA > 0);
	--Cau 10--
	ALTER TABLE KHACHHANG
	ADD CONSTRAINT CHECK_NGDK CHECK(NGDK>NGSINH);

			--QuanLyGiaoVu--

	--Cau 1--
	ALTER TABLE HOCVIEN ADD
	CONSTRAINT FK_HV_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);
	ALTER TABLE LOP ADD
	CONSTRAINT FK_LOP_GV FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV);
	ALTER TABLE LOP ADD
	CONSTRAINT FK_TRGLOP FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN(MAHV);
	ALTER TABLE GIAOVIEN ADD 
	CONSTRAINT FK_MAKHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);
	ALTER TABLE GIANGDAY ADD 
	CONSTRAINT FK_MAMH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH);
	ALTER TABLE KHOA ADD 
	CONSTRAINT FK_MAGV FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV);
	ALTER TABLE MONHOC ADD
	CONSTRAINT FK_MAKHOA_2 FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);
	ALTER TABLE DIEUKIEN ADD 
	CONSTRAINT FK_MAMH_TRUOC FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH);
	ALTER TABLE DIEUKIEN ADD
	CONSTRAINT FK_DK_MAMH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH);
	ALTER TABLE KETQUATHI ADD
	CONSTRAINT FK_MAHV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV);

	--Cau 3--
	ALTER TABLE HOCVIEN ADD
	CONSTRAINT CHECK_GT CHECK(GIOITINH IN ('Nam', 'Nu'));
	ALTER TABLE GIAOVIEN ADD
	CONSTRAINT CHECK_GTGV CHECK(GIOITINH IN('Nam', 'Nu'));
	--Cau 4--
	ALTER TABLE KETQUATHI ADD
	CONSTRAINT CHECK_DIEM CHECK 
	(
		DIEM BETWEEN 0 AND 10
		AND RIGHT(CAST(DIEM AS VARCHAR), 3) LIKE '.__'
	)
	--Cau 5--
	ALTER TABLE KETQUATHI ADD 
	CONSTRAINT CHECK_KETQUA CHECK
	(	
		(KQUA = 'Dat' AND DIEM BETWEEN 5 AND 10)
		OR (KQUA = 'Khong dat' AND DIEM < 5)
	)
	--Cau 6--
	ALTER TABLE KETQUATHI ADD
	CONSTRAINT CHECK_LANTHI CHECK (LANTHI <=3);
	--Cau 7--
	ALTER TABLE GIANGDAY ADD
	CONSTRAINT CHECK_HK CHECK (HOCKY BETWEEN 1 AND 3);
	--Cau 8--
	ALTER TABLE GIAOVIEN ADD
	CONSTRAINT CHECK_HOCVi CHECK (HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS'));